openapi: 3.0.3
info:
  title: Simple test API
  description: Simple test API
  version: 1.0.0
  contact:
    name: Gleb Ivashyn
    url: https://github.com/GlobeDaBoarder?tab=repositories
    email: glebivashyn@gmail.com
servers:
  - url: 'https://localhost:8080'
paths:
  /dogs/ok-endpoints/:
    get:
      summary: Get all dogs
      operationId: getAllDogs
      tags:
        - dogs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dog'
  /dogs/ok-endpoints/{id}:
    delete:
      summary: Delete dog by id
      operationId: deleteDogById
      tags:
        - dogs
      parameters:
        - name: id
          in: path
          description: Dog id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad Request
  /dogs/broken-endpoint/:
    get:
      summary: Broken
      operationId: broken
      deprecated: true # Done purely for visibility purposes in Swagger UI
      tags:
        - dogs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dog'
        '204':
          description: No Content
        '400':
          description: Bad Request
components:
  schemas:
    Dog:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
          format: int32
        breed:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string


  
